services:
  backend:
    build:
      context: ./backend
    container_name: credit-card-fraud-detection-backend
    environment:
      APP_NAME: BTC Tensor Lab API
      CORS_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
