services:
  frontend:
    build:
      context: ./frontend
    container_name: credit-card-fraud-detection-frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./frontend/src:/usr/share/nginx/src:ro
    ports:
      - "3000:80"
